### ISSUE TITLE
Lootcli should be updated to support the latest version of loot

### ISSUE THREAD

**Issue by LePresidente** [TanninOne/modorganizer-lootcli#5]
This is required for the latest release where skyrimse is supported

Main issue for tracking release : https://github.com/TanninOne/modorganizer/issues/1026

**Comment by ZachHaber** [comment]
So... Quick (or not so quick) question regarding this for @TanninOne: I'm wondering why the loot worker used a windows function for dynamically loading a dll into the program at runtime which causes the need to resolve variables and functions, instead of simply linking the dll into the program for compilation. 
` m_Library = LoadLibraryW(L"loot_api.dll");
  if (m_Library == nullptr) {
    throw std::runtime_error("failed to load loot_api.dll");
  } `
Is this something I can remove while I'm working on it and do the normal linkage to make my life easier?

**Comment by ZachHaber** [comment]
And here's an updated lootcli running. It's still not fully finished (need to figure out and add in some try catch statements) and try and figure out how to get MO to actually display the dirty/clean status.
Before:
![before](https://cloud.githubusercontent.com/assets/19843782/21514247/a694189c-cc88-11e6-9bf2-f5422e607490.PNG)
During:
![during](https://cloud.githubusercontent.com/assets/19843782/21514249/a8ce58a2-cc88-11e6-971d-9399106a21a5.PNG)
After:
![after](https://cloud.githubusercontent.com/assets/19843782/21514250/aa092616-cc88-11e6-89cc-a5f5a382ea01.PNG)

**Comment by TanninOne** [comment]
When you say "normal linkage" I guess you mean "load-time linking", as in: linking against a stub-lib.
This makes your life as a developer easier but there are at least two reasons to prefer dynamic / runtime linking:
a) Error reporting. If load-time linking fails (i.e. because the loot.dll was deleted or replaced with an incompatible one) the error message the user gets is fairly useless because it doesn't explain which library is missing. With runtime linking we handle the missing/incompatible dll in code and can provide proper guidance to the user (like: loot_api.dll is missing, go to https://github.com/loot/loot and download it there)
b) compatibility: With run-time linking we load only the functions we use and call them with the paramaters we think are right. As long as these calls are valid in the dll it is compatible. With load-time linking the signatures must match exactly (afaik) and additional symbols we don't even use may be loaded - depending on the optimization flags and decisions the compiler makes.
